### ISSUE TITLE
API docs link to Github files on canary branch

### ISSUE THREAD

**Issue by acorncom** [denali-js/denali#80] opened 2016-09-03 02:42 UTC
Which doesn't exist, leading to a Github 404

**Comment by knownasilya** [comment] 2016-09-07 02:31
Seems like https://github.com/denali-js/denali/blob/docs/config.js#L17 is the cause.

**Comment by davewasmer** [comment] 2016-09-07 02:37
That's part of it, but intentional. We want to have the version dropdown and the URLs refer to the `master` branch as "canary", so there is some "aliasing" functionality built in to the docs build process.

The problem here is that after the rename, the original ref name is overwritten in the data object that is eventually passed to the template. We should probably store the original ref name alongside the renamed version name.

Looks like that would need to be added around here: https://github.com/denali-js/denali/blob/docs/build/lib/build-version-meta.js#L8. The templates would also need to be updated too, to use the original ref name in the url.

**Comment by knownasilya** [comment] 2016-09-09 17:23
@acorncom do you have an example of one of these links? I can't find them.

**Comment by acorncom** [comment] 2016-09-09 17:28
@knownasilya Visit http://denali.js.org/canary/api/classes/JSONAPISerializer/, and click one of the links back to the source code
![screen shot 2016-09-09 at 11 28 08 am](https://cloud.githubusercontent.com/assets/802505/18396383/890d0238-7680-11e6-8e90-e9327250d98c.png)

**Comment by knownasilya** [comment] 2016-09-09 17:51
Should be fixed

**Closed by knownasilya** 2016-09-09 17:51 UTC
Labels: documentation
