### ISSUE TITLE
Do we want to allow integration tests for middleware calls?

### ISSUE THREAD

**Issue by acorncom** [denali-js/denali#129] opened 2016-10-07 17:33 UTC
Non-urgent, this is more of a long-term question.  But thought I should throw it out there in the interests of discussing what we want our testing system to be able to handle ...

I'm starting in on adding webhook functionality for the help wanted backend and have hit a snag when running integration tests against the testing system.

Specifically, I'm seeing this error when running tests:

```
  webhook issues
    POST /webhook/issues
      1) should create a issue
Unhandled rejection Error: write after end
    at writeAfterEnd (_stream_writable.js:166:12)
    at MockResponse.Writable.write (_stream_writable.js:217:5)
    at MockResponse.write (./denali-js/denali/node_modules/compression/index.js:88:18)
    at ErrorAction.render (./denali-js/denali/lib/runtime/action.js:195:24)
    at tryCatcher (./denali-js/denali/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (./denali-js/denali/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (./denali-js/denali/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (./denali-js/denali/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (./denali-js/denali/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (./denali-js/denali/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (./denali-js/denali/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (./denali-js/denali/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

When running doing the same type of POST to the server using a regular client instead of through the test suite, things work fine (or rather, I get the errors I was expecting 😀 )

**Comment by davewasmer** [comment] 2016-10-07 22:25
I have a feeling this is a bug in the new MockRequest/MockResponse classes. Not sure how middleware relates here. Is this bug reproducible on a branch of ember-help-wanted?

**Comment by acorncom** [comment] 2016-10-07 22:41
Yep, see this PR for details: https://github.com/ember-learn/ember-help-wanted-backend/pull/11  I skipped the test that was failing in the final commit (referenced above).  @sivakumar-kailasam may continue working on that branch (in which case it may not be the last commit when you take a look)

**Comment by acorncom** [comment] 2016-10-12 20:00
@davewasmer Is this type of issue actionable if I clean it up or would it be simpler to just close it?

**Comment by davewasmer** [comment] 2016-10-27 01:03
On second glance, I think this might have been a bug with your middleware? It looks like the compression middleware was trying to write to the response, but the response was already sent (I'm guessing by your middleware prior to the compression middleware running).

I'm closing for now, but if you're able to reproduce, feel free to reopen.

**Closed by davewasmer** 2016-10-27 01:03 UTC
Labels: package:testing
