### ISSUE TITLE
Include standard-version as part of denali publish

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali#364] opened 2017-07-12 16:13 UTC
Currently, you have to do test, then `standard-version`, then `denali publish`.

This could be wrapped into one, with an additional `--skip-versioning` flag.

**Comment by acburdine** [comment] 2017-07-12 17:13
Something to keep in mind for this is that the flags for standard-version would need to be added to `denali publish` as well.

**Comment by davewasmer** [comment] 2017-07-12 20:26
Duplicate of #298

**Closed by davewasmer** 2017-07-12 20:26 UTC
Labels: improvement, package:commands

**Comment by knownasilya** [comment] 2017-07-12 20:44
Ops 👍
